version: '3.3'

services:

  database:
    image: "postgres"
    restart: always
    env_file:
      - docker.env.database.sample
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - local
    ports:
      - "5432:5432"
    expose:
      - '5432'

  scheduler-backend:
    build: .
    image: scheduler-backend
    restart: always
    env_file:
      - docker.env.scheduler.sample
    networks:
      - local
    ports:
      - "3000:3000"
    expose:
      - '3000'
    depends_on:
      - database

volumes:
  database-data:

networks:
  local:
    driver: bridge
